name: Build my program
on: push

jobs:
  build:
    name: build name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        with:
          MY_NAME: "DEV"



