name: A workflow for my Hello World file
on: workflow_dispatch

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        with:
          MY_NAME: "Mona"
      - name: show env
        run: |
          echo "PWD = '`pwd`'"
          echo "===> LS:"
          ls
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: outputs/*


