name: A workflow for my Hello World file
on: workflow_dispatch

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        with:
          MESSAGE: "(Hello, Action! :-)"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "We are ready!"
          prerelease: false
          automatic_release_tag: latest
          files: outputs/*
      - name: show env
        run: |
          echo "ALL IS WELL"
